# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'begin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Begin(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 600)
        self.test_name = QtWidgets.QLineEdit(Form)
        self.test_name.setGeometry(QtCore.QRect(40, 60, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.test_name.setFont(font)
        self.test_name.setObjectName("test_name")
        self.test_count = QtWidgets.QLineEdit(Form)
        self.test_count.setGeometry(QtCore.QRect(40, 150, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.test_count.setFont(font)
        self.test_count.setObjectName("test_count")
        self.create = QtWidgets.QPushButton(Form)
        self.create.setGeometry(QtCore.QRect(70, 290, 251, 81))
        self.create.setObjectName("create")
        self.Back = QtWidgets.QPushButton(Form)
        self.Back.setGeometry(QtCore.QRect(70, 410, 251, 81))
        self.Back.setObjectName("Back")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.test_name.setPlaceholderText(_translate("Form", "Введите название теста"))
        self.test_count.setPlaceholderText(_translate("Form", "Укажите кол-во вопросов"))
        self.create.setText(_translate("Form", "Начать"))
        self.Back.setText(_translate("Form", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
