# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'do_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Do_test(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 600)
        self.question_count = QtWidgets.QComboBox(Form)
        self.question_count.setGeometry(QtCore.QRect(300, 30, 69, 22))
        self.question_count.setObjectName("question_count")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(180, 30, 111, 21))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.question_text = QtWidgets.QLabel(Form)
        self.question_text.setGeometry(QtCore.QRect(30, 70, 351, 101))
        self.question_text.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.question_text.setLineWidth(2)
        self.question_text.setTextFormat(QtCore.Qt.AutoText)
        self.question_text.setScaledContents(False)
        self.question_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.question_text.setWordWrap(True)
        self.question_text.setObjectName("question_text")
        self.user_answer = QtWidgets.QLineEdit(Form)
        self.user_answer.setGeometry(QtCore.QRect(30, 210, 341, 31))
        self.user_answer.setObjectName("user_answer")
        self.variant_1 = QtWidgets.QLabel(Form)
        self.variant_1.setGeometry(QtCore.QRect(40, 280, 231, 21))
        self.variant_1.setObjectName("variant_1")
        self.variant_2 = QtWidgets.QLabel(Form)
        self.variant_2.setGeometry(QtCore.QRect(40, 320, 231, 21))
        self.variant_2.setObjectName("variant_2")
        self.variant_3 = QtWidgets.QLabel(Form)
        self.variant_3.setGeometry(QtCore.QRect(40, 360, 231, 21))
        self.variant_3.setObjectName("variant_3")
        self.variant_4 = QtWidgets.QLabel(Form)
        self.variant_4.setGeometry(QtCore.QRect(40, 400, 231, 21))
        self.variant_4.setObjectName("variant_4")
        self.true_1 = QtWidgets.QCheckBox(Form)
        self.true_1.setGeometry(QtCore.QRect(290, 280, 70, 17))
        self.true_1.setText("")
        self.true_1.setObjectName("true_1")
        self.true_2 = QtWidgets.QCheckBox(Form)
        self.true_2.setGeometry(QtCore.QRect(290, 320, 70, 17))
        self.true_2.setText("")
        self.true_2.setObjectName("true_2")
        self.true_3 = QtWidgets.QCheckBox(Form)
        self.true_3.setGeometry(QtCore.QRect(290, 360, 70, 17))
        self.true_3.setText("")
        self.true_3.setObjectName("true_3")
        self.true_4 = QtWidgets.QCheckBox(Form)
        self.true_4.setGeometry(QtCore.QRect(290, 400, 70, 17))
        self.true_4.setText("")
        self.true_4.setObjectName("true_4")
        self.next = QtWidgets.QPushButton(Form)
        self.next.setGeometry(QtCore.QRect(240, 500, 131, 51))
        self.next.setObjectName("next")
        self.end_test = QtWidgets.QPushButton(Form)
        self.end_test.setGeometry(QtCore.QRect(50, 500, 131, 21))
        self.end_test.setObjectName("end_test")
        self.exit = QtWidgets.QPushButton(Form)
        self.exit.setGeometry(QtCore.QRect(50, 530, 131, 21))
        self.exit.setObjectName("exit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Вопрос №"))
        self.question_text.setText(_translate("Form", "Text"))
        self.user_answer.setPlaceholderText(_translate("Form", "Введите ответ..."))
        self.variant_1.setText(_translate("Form", "TextLabel"))
        self.variant_2.setText(_translate("Form", "TextLabel"))
        self.variant_3.setText(_translate("Form", "TextLabel"))
        self.variant_4.setText(_translate("Form", "TextLabel"))
        self.next.setText(_translate("Form", "Далее"))
        self.end_test.setText(_translate("Form", "Закончить"))
        self.exit.setText(_translate("Form", "Выйти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
