# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 600)
        self.line_login = QtWidgets.QLineEdit(Form)
        self.line_login.setGeometry(QtCore.QRect(40, 80, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_login.setFont(font)
        self.line_login.setInputMask("")
        self.line_login.setText("")
        self.line_login.setObjectName("line_login")
        self.line_password = QtWidgets.QLineEdit(Form)
        self.line_password.setGeometry(QtCore.QRect(40, 150, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_password.setFont(font)
        self.line_password.setInputMask("")
        self.line_password.setText("")
        self.line_password.setFrame(True)
        self.line_password.setObjectName("line_password")
        self.pushButton_login = QtWidgets.QPushButton(Form)
        self.pushButton_login.setGeometry(QtCore.QRect(60, 310, 281, 71))
        self.pushButton_login.setObjectName("pushButton_login")
        self.pushButton_register = QtWidgets.QPushButton(Form)
        self.pushButton_register.setGeometry(QtCore.QRect(60, 400, 281, 71))
        self.pushButton_register.setObjectName("pushButton_register")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.line_login.setPlaceholderText(_translate("Form", "Логин..."))
        self.line_password.setPlaceholderText(_translate("Form", "Пароль..."))
        self.pushButton_login.setText(_translate("Form", "Войти"))
        self.pushButton_register.setText(_translate("Form", "Регистрация"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
