# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'question_creator.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Question_creator(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 600)
        self.question_number = QtWidgets.QComboBox(Form)
        self.question_number.setGeometry(QtCore.QRect(300, 20, 81, 22))
        self.question_number.setObjectName("question_number")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 10, 251, 41))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.text_question = QtWidgets.QTextEdit(Form)
        self.text_question.setGeometry(QtCore.QRect(20, 60, 361, 71))
        self.text_question.setObjectName("text_question")
        self.answer = QtWidgets.QLineEdit(Form)
        self.answer.setGeometry(QtCore.QRect(20, 170, 361, 31))
        self.answer.setObjectName("answer")
        self.change_type = QtWidgets.QCheckBox(Form)
        self.change_type.setGeometry(QtCore.QRect(20, 220, 181, 17))
        self.change_type.setObjectName("change_type")
        self.variant_1 = QtWidgets.QLineEdit(Form)
        self.variant_1.setEnabled(False)
        self.variant_1.setGeometry(QtCore.QRect(20, 260, 211, 31))
        self.variant_1.setObjectName("variant_1")
        self.variant_4 = QtWidgets.QLineEdit(Form)
        self.variant_4.setEnabled(False)
        self.variant_4.setGeometry(QtCore.QRect(20, 410, 211, 31))
        self.variant_4.setObjectName("variant_4")
        self.variant_3 = QtWidgets.QLineEdit(Form)
        self.variant_3.setEnabled(False)
        self.variant_3.setGeometry(QtCore.QRect(20, 360, 211, 31))
        self.variant_3.setObjectName("variant_3")
        self.variant_2 = QtWidgets.QLineEdit(Form)
        self.variant_2.setEnabled(False)
        self.variant_2.setGeometry(QtCore.QRect(20, 310, 211, 31))
        self.variant_2.setObjectName("variant_2")
        self.true_variant_2 = QtWidgets.QCheckBox(Form)
        self.true_variant_2.setEnabled(False)
        self.true_variant_2.setGeometry(QtCore.QRect(250, 320, 141, 17))
        self.true_variant_2.setObjectName("true_variant_2")
        self.true_variant_3 = QtWidgets.QCheckBox(Form)
        self.true_variant_3.setEnabled(False)
        self.true_variant_3.setGeometry(QtCore.QRect(250, 370, 141, 17))
        self.true_variant_3.setObjectName("true_variant_3")
        self.true_variant_4 = QtWidgets.QCheckBox(Form)
        self.true_variant_4.setEnabled(False)
        self.true_variant_4.setGeometry(QtCore.QRect(250, 420, 141, 17))
        self.true_variant_4.setObjectName("true_variant_4")
        self.true_variant_1 = QtWidgets.QCheckBox(Form)
        self.true_variant_1.setEnabled(False)
        self.true_variant_1.setGeometry(QtCore.QRect(250, 270, 141, 17))
        self.true_variant_1.setObjectName("true_variant_1")
        self.save_question = QtWidgets.QPushButton(Form)
        self.save_question.setGeometry(QtCore.QRect(20, 490, 171, 61))
        self.save_question.setObjectName("save_question")
        self.exit = QtWidgets.QPushButton(Form)
        self.exit.setGeometry(QtCore.QRect(210, 490, 171, 61))
        self.exit.setObjectName("exit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Номер вопроса"))
        self.text_question.setPlaceholderText(_translate("Form", "Введите вопрос..."))
        self.answer.setPlaceholderText(_translate("Form", "Введите ответ..."))
        self.change_type.setText(_translate("Form", "Вопрос с вариантами ответа"))
        self.variant_1.setPlaceholderText(_translate("Form", "Вариант 1"))
        self.variant_4.setPlaceholderText(_translate("Form", "Вариант 4"))
        self.variant_3.setPlaceholderText(_translate("Form", "Вариант 3"))
        self.variant_2.setPlaceholderText(_translate("Form", "Вариант 2"))
        self.true_variant_2.setText(_translate("Form", "Правильный ответ"))
        self.true_variant_3.setText(_translate("Form", "Правильный ответ"))
        self.true_variant_4.setText(_translate("Form", "Правильный ответ"))
        self.true_variant_1.setText(_translate("Form", "Правильный ответ"))
        self.save_question.setText(_translate("Form", "Сохранить вопрос"))
        self.exit.setText(_translate("Form", "Выйти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
