# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Test_list(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(400, 600)
        self.create_test = QtWidgets.QPushButton(Form)
        self.create_test.setGeometry(QtCore.QRect(80, 410, 241, 61))
        self.create_test.setObjectName("create_test")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 20, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.test_list = QtWidgets.QComboBox(Form)
        self.test_list.setGeometry(QtCore.QRect(50, 170, 291, 51))
        self.test_list.setObjectName("test_list")
        self.begin_test = QtWidgets.QPushButton(Form)
        self.begin_test.setGeometry(QtCore.QRect(80, 340, 241, 61))
        self.begin_test.setObjectName("begin_test")
        self.comment = QtWidgets.QLabel(Form)
        self.comment.setGeometry(QtCore.QRect(40, 80, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comment.setFont(font)
        self.comment.setAlignment(QtCore.Qt.AlignCenter)
        self.comment.setObjectName("comment")
        self.back = QtWidgets.QPushButton(Form)
        self.back.setGeometry(QtCore.QRect(80, 480, 241, 61))
        self.back.setObjectName("back")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.create_test.setText(_translate("Form", "Создать тест"))
        self.label.setText(_translate("Form", "Добро пожаловать"))
        self.begin_test.setText(_translate("Form", "Начать тест"))
        self.comment.setText(_translate("Form", "Выбирете тест"))
        self.back.setText(_translate("Form", "Выйти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
